### ISSUE TITLE
Cannot access a disposed object when Token credentials are invalid

### ISSUE THREAD

**Issue by Bogatinov** [rivr-io/rivr-dotnet-client#1]
## Configuration
- dotNET 4.8
- ASPNET MVC 5 project
- Rivr 1.0.7 with binding redirects in `Web.config` for `Microsoft.Extensions.*` libraries
- tested in both Visual Studio 2022, 2019 and VS Code with console project and binding redirects

## Repro steps
1. Create a `Config` with invalid credentials, that will not provide you access
```cs
new Config("asdsda", "asdasda", Environment.Test)
```
2. Try to call any API from the library
```cs
await client.GetHealthSecureAsync();
```
3. `RefreshMerchantCredentialsAsync` tries to connect to create a valid token
4. `HttpClientExtensions` creates a new `StringContent` from `merchantCredentials`
5. `await client.PostAsync(url, content, cancellationToken)` throws exception that `content` is already disposed
![image](https://github.com/user-attachments/assets/15e29d5f-fbf4-420b-8f76-3b3acb4c0d06)

## Debug steps
1. `HttpResponseMessageExtensions.EnsureSuccessfulResponseAsync` tries to access `connect/token`, but the payload is already disposed
1. `HttpContent.ReadAsStringAsync` checks that the payload is not disposed, before calling `HttpClient.PostAsync()`
2. `this HttpResponseMessage message` has status code `BadRequest` after trying `connect/token`
3. `message.Content` is not disposed, but `message.RequestMessage.Content` is disposed

In our example, `content` is `connect/token` payload (i.e. `clientId` and `clientSecret`)

This looks like the `StringContent` is disposed by another method, before the `TaskAwaiter` completes the async delegate action in `ReadAsStringAsync()`

**Comment by mikeeast** [comment]
This may be an issue in .NET 4.8 only. I cannot reproduce this in .NET Core 6. I'll create a sample project using .NET 4.8 to see if I can reproduce.

**Comment by Bogatinov** [comment]
Possible, I'm investigating, since to use Rivr in dotNET Framework 4.5 and above, we need to apply a lot of Binding redirects
https://nickcraver.com/blog/2020/02/11/binding-redirects/

This means the library uses dotNET Core specific code, and in runtime we should specify which version of packages to use. Otherwise, there are runtime exceptions with `System.Text.Json` and other Core internals to `Microsoft.Extensions.*`

```xml
 <dependentAssembly>
   <assemblyIdentity name="Microsoft.Extensions.Caching.Memory" culture="neutral" publicKeyToken="adb9793829ddae60" />
   <bindingRedirect oldVersion="0.0.0.0-8.0.0.1" newVersion="8.0.0.1" />
 </dependentAssembly>
 <dependentAssembly>
   <assemblyIdentity name="Microsoft.Extensions.Configuration.Binder" culture="neutral" publicKeyToken="adb9793829ddae60" />
   <bindingRedirect oldVersion="0.0.0.0-8.0.0.2" newVersion="8.0.0.2" />
 </dependentAssembly>
 <dependentAssembly>
   <assemblyIdentity name="Microsoft.Extensions.DependencyInjection.Abstractions" culture="neutral" publicKeyToken="adb9793829ddae60" />
   <bindingRedirect oldVersion="0.0.0.0-8.0.0.2" newVersion="8.0.0.2" />
 </dependentAssembly>
 <dependentAssembly>
   <assemblyIdentity name="Microsoft.Extensions.Http" culture="neutral" publicKeyToken="adb9793829ddae60" />
   <bindingRedirect oldVersion="0.0.0.0-8.0.0.1" newVersion="8.0.0.1" />
 </dependentAssembly>
 <dependentAssembly>
   <assemblyIdentity name="Microsoft.Extensions.Logging.Abstractions" culture="neutral" publicKeyToken="adb9793829ddae60" />
   <bindingRedirect oldVersion="0.0.0.0-8.0.0.2" newVersion="8.0.0.2" />
 </dependentAssembly>
```

**Comment by Bogatinov** [comment]
latest changes in 1.0.7 and 1.0.10 fixes the issue in net48 with Disposed object
![image](https://github.com/user-attachments/assets/0159215f-9d21-4c34-b40a-41c284cc36af)
